=== Energinet-DataHub/opengeh-edi/source/B2B.Transactions.CimMessageAdapter.Tests/urn-ediel-org-structure-requestchangeofsupplier-0-1.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:cim="urn:ediel.org:structure:requestchangeofsupplier:0:1" xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:sawsdl="http://www.w3.org/ns/sawsdl" xmlns:cimp="http://www.iec.ch/cimprofile" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:ediel.org:structure:requestchangeofsupplier:0:1" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:import namespace="urn:entsoe.eu:wgedi:codelists" schemaLocation="urn-entsoe-eu-wgedi-codelists.xsd"/>
	<xs:element name="RequestChangeOfSupplier_MarketDocument" type="cim:RequestChangeOfSupplier_MarketDocument"/>
	<xs:simpleType name="MeasurementPointID_String-base" sawsdl:modelReference="http://iec.ch/TC57/2010/CIM-schema-cim15#String">
		<xs:restriction base="xs:string">
			<xs:maxLength value="35"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="MeasurementPointID_String" sawsdl:modelReference="http://iec.ch/TC57/2010/CIM-schema-cim15#String">
		<xs:simpleContent>
			<xs:extension base="cim:MeasurementPointID_String-base">
				<xs:attribute name="codingScheme" type="ecl:CodingSchemeTypeList" use="required"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:simpleType name="PartyID_String-base" sawsdl:modelReference="http://iec.ch/TC57/2010/CIM-schema-cim15#String">
		<xs:restriction base="xs:string">
			<xs:maxLength value="16"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="PartyID_String" sawsdl:modelReference="http://iec.ch/TC57/2010/CIM-schema-cim15#String">
		<xs:simpleContent>
			<xs:extension base="cim:PartyID_String-base">
				<xs:attribute name="codingScheme" type="ecl:CodingSchemeTypeList" use="required"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="MktActivityRecord" sawsdl:modelReference="http://iec.ch/TC57/2010/CIM-schema-cim15#MktActivityRecord">
		<xs:sequence>
			<xs:element name="mRID" type="xs:string" minOccurs="1" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/2010/CIM-schema-cim15#IdentifiedObject.mRID"/>
			<xs:element name="businessProcessReference_MktActivityRecord.mRID" type="xs:string" minOccurs="0" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/2010/CIM-schema-cim15#IdentifiedObject.mRID"/>
			<xs:element name="marketEvaluationPoint.mRID" type="cim:MeasurementPointID_String" minOccurs="1" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/2010/CIM-schema-cim15#IdentifiedObject.mRID"/>
			<xs:element name="marketEvaluationPoint.energySupplier_MarketParticipant.mRID" type="cim:PartyID_String" minOccurs="1" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/2010/CIM-schema-cim15#IdentifiedObject.mRID"/>
			<xs:element name="marketEvaluationPoint.balanceResponsibleParty_MarketParticipant.mRID" type="cim:PartyID_String" minOccurs="0" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/2010/CIM-schema-cim15#IdentifiedObject.mRID"/>
			<xs:element name="marketEvaluationPoint.shipper_MarketParticipant.mRID" type="cim:PartyID_String" minOccurs="0" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/2010/CIM-schema-cim15#IdentifiedObject.mRID"/>
			<xs:element name="marketEvaluationPoint.customer_MarketParticipant.mRID" type="cim:PartyID_String" minOccurs="0" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/2010/CIM-schema-cim15#IdentifiedObject.mRID"/>
			<xs:element name="marketEvaluationPoint.customer_MarketParticipant.name" type="xs:string" minOccurs="0" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/2010/CIM-schema-cim15#IdentifiedObject.name"/>
			<xs:element name="start_DateAndOrTime.dateTime" type="xs:dateTime" minOccurs="1" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/2010/CIM-schema-cim15#DateAndOrTime.dateTime"/>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="MessageKind_String" sawsdl:modelReference="http://iec.ch/TC57/2010/CIM-schema-cim15#String">
		<xs:restriction base="ecl:MessageTypeList"/>
	</xs:simpleType>
	<xs:simpleType name="ProcessKind_String" sawsdl:modelReference="http://iec.ch/TC57/2010/CIM-schema-cim15#String">
		<xs:restriction base="ecl:ProcessTypeList"/>
	</xs:simpleType>
	<xs:simpleType name="BusinessSectorKind_String" sawsdl:modelReference="http://iec.ch/TC57/2010/CIM-schema-cim15#String">
		<xs:restriction base="ecl:BusinessSectorTypeList"/>
	</xs:simpleType>
	<xs:simpleType name="MarketRoleKind_String" sawsdl:modelReference="http://iec.ch/TC57/2010/CIM-schema-cim15#String">
		<xs:restriction base="ecl:RoleTypeList"/>
	</xs:simpleType>
	<xs:complexType name="RequestChangeOfSupplier_MarketDocument" sawsdl:modelReference="http://iec.ch/TC57/2010/CIM-schema-cim15#MarketDocument">
		<xs:sequence>
			<xs:element name="mRID" type="xs:string" minOccurs="1" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/2010/CIM-schema-cim15#IdentifiedObject.mRID"/>
			<xs:element name="type" type="cim:MessageKind_String" default="392" minOccurs="1" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/2010/CIM-schema-cim15#Document.type"/>
			<xs:element name="process.processType" type="cim:ProcessKind_String" minOccurs="1" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/2010/CIM-schema-cim15#Process.processType"/>
			<xs:element name="businessSector.type" type="cim:BusinessSectorKind_String" minOccurs="0" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/2010/CIM-schema-cim15#BusinessSector.type"/>
			<xs:element name="sender_MarketParticipant.mRID" type="cim:PartyID_String" minOccurs="1" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/2010/CIM-schema-cim15#IdentifiedObject.mRID"/>
			<xs:element name="sender_MarketParticipant.marketRole.type" type="cim:MarketRoleKind_String" minOccurs="1" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/2010/CIM-schema-cim15#MarketRole.type"/>
			<xs:element name="receiver_MarketParticipant.mRID" type="cim:PartyID_String" minOccurs="1" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/2010/CIM-schema-cim15#IdentifiedObject.mRID"/>
			<xs:element name="receiver_MarketParticipant.marketRole.type" type="cim:MarketRoleKind_String" minOccurs="1" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/2010/CIM-schema-cim15#MarketRole.type"/>
			<xs:element name="createdDateTime" type="xs:dateTime" minOccurs="1" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/2010/CIM-schema-cim15#Document.createdDateTime"/>
			<xs:element name="MktActivityRecord" type="cim:MktActivityRecord" minOccurs="1" maxOccurs="unbounded" sawsdl:modelReference="http://iec.ch/TC57/2010/CIM-schema-cim15#MarketDocument.MktActivityRecord"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== Energinet-DataHub/opengeh-edi/source/Tests/CimMessageAdapter/Messages/xml/Confirm request Change of Supplier.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright 2020 Energinet DataHub A/S

Licensed under the Apache License, Version 2.0 (the "License2");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->
<cim:RequestChangeOfSupplier_MarketDocument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:cim="urn:ediel.org:structure:requestchangeofsupplier:0:1" xsi:schemaLocation="urn:ediel.org:structure:requestchangeofsupplier:0:1 urn-ediel-org-structure-requestchangeofsupplier-0-1.xsd">
    <cim:mRID>26E65F44-5D67-443A-98A8-95FF40178A25</cim:mRID>
    <cim:type>392</cim:type>
    <cim:process.processType>E65</cim:process.processType>
    <cim:businessSector.type>23</cim:businessSector.type>
    <cim:sender_MarketParticipant.mRID codingScheme="A10">1234</cim:sender_MarketParticipant.mRID>
    <cim:sender_MarketParticipant.marketRole.type>DDQ</cim:sender_MarketParticipant.marketRole.type>
    <cim:receiver_MarketParticipant.mRID codingScheme="A10">5790001330552</cim:receiver_MarketParticipant.mRID>
    <cim:receiver_MarketParticipant.marketRole.type>DDZ</cim:receiver_MarketParticipant.marketRole.type>
    <cim:createdDateTime>2022-09-07T09:30:47Z</cim:createdDateTime>
    <cim:MktActivityRecord>
        <cim:mRID>A106081F-B5CA-4090-88E1-F45849E61C37</cim:mRID>
        <cim:marketEvaluationPoint.mRID codingScheme="A10">577489701109152347</cim:marketEvaluationPoint.mRID>
        <cim:marketEvaluationPoint.energySupplier_MarketParticipant.mRID codingScheme="A10">5678</cim:marketEvaluationPoint.energySupplier_MarketParticipant.mRID>
        <cim:marketEvaluationPoint.customer_MarketParticipant.mRID codingScheme="ARR" >0801741527</cim:marketEvaluationPoint.customer_MarketParticipant.mRID>
        <cim:marketEvaluationPoint.customer_MarketParticipant.name>Jan Hansen</cim:marketEvaluationPoint.customer_MarketParticipant.name>
        <cim:start_DateAndOrTime.dateTime>2022-06-27T22:00:00Z</cim:start_DateAndOrTime.dateTime>
    </cim:MktActivityRecord>
</cim:RequestChangeOfSupplier_MarketDocument>
