=== Energinet-DataHub/opengeh-edi/source/IncomingMessages.Domain/Schemas/Cim/Xml/Schemas/urn-ediel-org-measure-notifyvalidatedmeasuredata-0-1.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:cim="urn:ediel.org:measure:notifyvalidatedmeasuredata:0:1" xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:sawsdl="http://www.w3.org/ns/sawsdl" xmlns:cimp="http://www.iec.ch/cimprofile" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:ediel.org:measure:notifyvalidatedmeasuredata:0:1" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:import namespace="urn:entsoe.eu:wgedi:codelists" schemaLocation="urn-entsoe-eu-wgedi-codelists.xsd"/>
	<xs:element name="NotifyValidatedMeasureData_MarketDocument" type="cim:NotifyValidatedMeasureData_MarketDocument"/>
	<xs:simpleType name="MessageKind_String" sawsdl:modelReference="http://iec.ch/TC57/CIM101#String">
		<xs:restriction base="ecl:MessageTypeList"/>
	</xs:simpleType>
	<xs:simpleType name="ProcessKind_String" sawsdl:modelReference="http://iec.ch/TC57/CIM101#String">
		<xs:restriction base="ecl:ProcessTypeList"/>
	</xs:simpleType>
	<xs:simpleType name="BusinessSectorKind_String" sawsdl:modelReference="http://iec.ch/TC57/CIM101#String">
		<xs:restriction base="ecl:BusinessSectorTypeList"/>
	</xs:simpleType>
	<xs:simpleType name="PartyID_String-base" sawsdl:modelReference="http://iec.ch/TC57/CIM101#String">
		<xs:restriction base="xs:string">
			<xs:maxLength value="16"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="PartyID_String" sawsdl:modelReference="http://iec.ch/TC57/CIM101#String">
		<xs:simpleContent>
			<xs:extension base="cim:PartyID_String-base">
				<xs:attribute name="codingScheme" type="ecl:CodingSchemeTypeList" use="required"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:simpleType name="MarketRoleKind_String" sawsdl:modelReference="http://iec.ch/TC57/CIM101#String">
		<xs:restriction base="ecl:RoleTypeList"/>
	</xs:simpleType>
	<xs:complexType name="NotifyValidatedMeasureData_MarketDocument" sawsdl:modelReference="http://iec.ch/TC57/CIM101#MarketDocument">
		<xs:sequence>
			<xs:element name="mRID" type="xs:string" minOccurs="1" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/CIM101#IdentifiedObject.mRID"/>
			<xs:element name="type" type="cim:MessageKind_String" default="E66" minOccurs="1" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/CIM101#Document.type"/>
			<xs:element name="process.processType" type="cim:ProcessKind_String" minOccurs="1" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/CIM101#Process.processType"/>
			<xs:element name="businessSector.type" type="cim:BusinessSectorKind_String" minOccurs="0" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/CIM101#BusinessSector.type"/>
			<xs:element name="sender_MarketParticipant.mRID" type="cim:PartyID_String" minOccurs="1" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/CIM101#IdentifiedObject.mRID"/>
			<xs:element name="sender_MarketParticipant.marketRole.type" type="cim:MarketRoleKind_String" minOccurs="1" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/CIM101#MarketRole.type"/>
			<xs:element name="receiver_MarketParticipant.mRID" type="cim:PartyID_String" minOccurs="1" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/CIM101#IdentifiedObject.mRID"/>
			<xs:element name="receiver_MarketParticipant.marketRole.type" type="cim:MarketRoleKind_String" minOccurs="1" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/CIM101#MarketRole.type"/>
			<xs:element name="createdDateTime" type="xs:dateTime" minOccurs="1" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/CIM101#Document.createdDateTime"/>
			<xs:element name="Series" type="cim:Series" minOccurs="0" maxOccurs="unbounded" sawsdl:modelReference="http://iec.ch/TC57/CIM101#MarketDocument.Series"/>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="Position_Integer" sawsdl:modelReference="http://iec.ch/TC57/CIM101#Integer">
		<xs:restriction base="xs:integer">
			<xs:maxInclusive value="999999"/>
			<xs:minInclusive value="1"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Quality_String" sawsdl:modelReference="http://iec.ch/TC57/CIM101#String">
		<xs:restriction base="ecl:QualityTypeList"/>
	</xs:simpleType>
	<xs:complexType name="Point" sawsdl:modelReference="http://iec.ch/TC57/CIM101#Point">
		<xs:sequence>
			<xs:element name="position" type="cim:Position_Integer" minOccurs="1" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/CIM101#Point.position"/>
			<xs:element name="quantity" type="xs:decimal" minOccurs="0" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/CIM101#Point.quantity"/>
			<xs:element name="quality" type="cim:Quality_String" minOccurs="0" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/CIM101#Point.quality"/>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="MeasurementPointID_String-base" sawsdl:modelReference="http://iec.ch/TC57/CIM101#String">
		<xs:restriction base="xs:string">
			<xs:maxLength value="35"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="MeasurementPointID_String" sawsdl:modelReference="http://iec.ch/TC57/CIM101#String">
		<xs:simpleContent>
			<xs:extension base="cim:MeasurementPointID_String-base">
				<xs:attribute name="codingScheme" type="ecl:CodingSchemeTypeList" use="required"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:simpleType name="MarketEvaluationPointKind_String" sawsdl:modelReference="http://iec.ch/TC57/CIM101#String">
		<xs:restriction base="ecl:MeteringPointTypeList"/>
	</xs:simpleType>
	<xs:simpleType name="AreaID_String-base" sawsdl:modelReference="http://iec.ch/TC57/CIM101#String">
		<xs:restriction base="xs:string">
			<xs:maxLength value="18"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="AreaID_String" sawsdl:modelReference="http://iec.ch/TC57/CIM101#String">
		<xs:simpleContent>
			<xs:extension base="cim:AreaID_String-base">
				<xs:attribute name="codingScheme" type="ecl:CodingSchemeTypeList" use="required"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:simpleType name="MeasurementUnitKind_String" sawsdl:modelReference="http://iec.ch/TC57/CIM101#String">
		<xs:restriction base="ecl:UnitOfMeasureTypeList"/>
	</xs:simpleType>
	<xs:complexType name="Series" sawsdl:modelReference="http://iec.ch/TC57/CIM101#Series">
		<xs:sequence>
			<xs:element name="mRID" type="xs:string" minOccurs="1" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/CIM101#IdentifiedObject.mRID"/>
			<xs:element name="originalTransactionIDReference_Series.mRID" type="xs:string" minOccurs="0" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/CIM101#IdentifiedObject.mRID"/>
			<xs:element name="marketEvaluationPoint.mRID" type="cim:MeasurementPointID_String" minOccurs="1" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/CIM101#IdentifiedObject.mRID"/>
			<xs:element name="marketEvaluationPoint.type" type="cim:MarketEvaluationPointKind_String" minOccurs="1" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/CIM101#Ext_MarketEvaluationPoint.type"/>
			<xs:element name="registration_DateAndOrTime.dateTime" type="xs:dateTime" minOccurs="1" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/CIM101#DateAndOrTime.dateTime"/>
			<xs:element name="in_Domain.mRID" type="cim:AreaID_String" minOccurs="0" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/CIM101#IdentifiedObject.mRID"/>
			<xs:element name="out_Domain.mRID" type="cim:AreaID_String" minOccurs="0" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/CIM101#IdentifiedObject.mRID"/>
			<xs:element name="product" type="xs:string" minOccurs="0" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/CIM101#TimeSeries.product"/>
			<xs:element name="quantity_Measure_Unit.name" type="cim:MeasurementUnitKind_String" minOccurs="1" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/CIM101#Unit.name"/>
			<xs:element name="Period" type="cim:Series_Period" minOccurs="1" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/CIM101#Series.Period"/>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="YMDHM_DateTime" sawsdl:modelReference="http://iec.ch/TC57/CIM101#DateTime">
		<xs:restriction base="xs:string">
			<xs:pattern value="((([0-9]{4})[\-](0[13578]|1[02])[\-](0[1-9]|[12][0-9]|3[01])|([0-9]{4})[\-]((0[469])|(11))[\-](0[1-9]|[12][0-9]|30))T(([01][0-9]|2[0-3]):[0-5][0-9])Z)|(([13579][26][02468][048]|[13579][01345789](0)[48]|[13579][01345789][2468][048]|[02468][048][02468][048]|[02468][1235679](0)[48]|[02468][1235679][2468][048]|[0-9][0-9][13579][26])[\-](02)[\-](0[1-9]|1[0-9]|2[0-9])T(([01][0-9]|2[0-3]):[0-5][0-9])Z)|(([13579][26][02468][1235679]|[13579][01345789](0)[01235679]|[13579][01345789][2468][1235679]|[02468][048][02468][1235679]|[02468][1235679](0)[01235679]|[02468][1235679][2468][1235679]|[0-9][0-9][13579][01345789])[\-](02)[\-](0[1-9]|1[0-9]|2[0-8])T(([01][0-9]|2[0-3]):[0-5][0-9])Z)"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="ESMP_DateTimeInterval" sawsdl:modelReference="http://iec.ch/TC57/CIM101#DateTimeInterval">
		<xs:sequence>
			<xs:element name="start" type="cim:YMDHM_DateTime" minOccurs="1" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/CIM101#DateTimeInterval.start"/>
			<xs:element name="end" type="cim:YMDHM_DateTime" minOccurs="1" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/CIM101#DateTimeInterval.end"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Series_Period" sawsdl:modelReference="http://iec.ch/TC57/CIM101#Period">
		<xs:sequence>
			<xs:element name="resolution" type="xs:duration" minOccurs="1" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/CIM101#Period.resolution"/>
			<xs:element name="timeInterval" type="cim:ESMP_DateTimeInterval" minOccurs="1" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/CIM101#Period.timeInterval"/>
			<xs:element name="Point" type="cim:Point" minOccurs="1" maxOccurs="unbounded" sawsdl:modelReference="http://iec.ch/TC57/CIM101#Period.Point"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== Energinet-DataHub/opengeh-edi/source/Tests/CimMessageAdapter/Messages/xml/MeteredDataForMeteringPoint/ValidMeteredDataForMeteringPoint.xml
<?xml version="1.0" encoding="UTF-8"?>
<cim:NotifyValidatedMeasureData_MarketDocument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:cim="urn:ediel.org:measure:notifyvalidatedmeasuredata:0:1" xsi:schemaLocation="urn:ediel.org:measure:notifyvalidatedmeasuredata:0:1 urn-ediel-org-measure-notifyvalidatedmeasuredata-0-1.xsd">
    <cim:mRID>111131835</cim:mRID>
    <cim:type>E66</cim:type>
    <cim:process.processType>E23</cim:process.processType>
    <cim:businessSector.type>23</cim:businessSector.type>
    <cim:sender_MarketParticipant.mRID codingScheme="A10">5790001330552</cim:sender_MarketParticipant.mRID>
    <cim:sender_MarketParticipant.marketRole.type>MDR</cim:sender_MarketParticipant.marketRole.type>
    <cim:receiver_MarketParticipant.mRID codingScheme="A10">5790000432752</cim:receiver_MarketParticipant.mRID>
    <cim:receiver_MarketParticipant.marketRole.type>DGL</cim:receiver_MarketParticipant.marketRole.type>
    <cim:createdDateTime>2024-07-30T07:30:54Z</cim:createdDateTime>
    <cim:Series>
        <cim:mRID>4413675032_5080574373</cim:mRID>
        <cim:originalTransactionIDReference_Series.mRID>C1875000</cim:originalTransactionIDReference_Series.mRID>
        <cim:marketEvaluationPoint.mRID codingScheme="A10">571313000000002000</cim:marketEvaluationPoint.mRID>
        <cim:marketEvaluationPoint.type>E18</cim:marketEvaluationPoint.type>
        <cim:registration_DateAndOrTime.dateTime>2022-12-17T07:30:00Z</cim:registration_DateAndOrTime.dateTime>
        <cim:product>8716867000030</cim:product>
        <cim:quantity_Measure_Unit.name>KWH</cim:quantity_Measure_Unit.name>
        <cim:Period>
            <cim:resolution>PT1H</cim:resolution>
            <cim:timeInterval>
                <cim:start>2024-06-28T22:00Z</cim:start>
                <cim:end>2024-06-29T22:00Z</cim:end>
            </cim:timeInterval>
            <cim:Point>
                <cim:position>1</cim:position>
                <cim:quantity>56</cim:quantity>
                <cim:quality>A03</cim:quality>
            </cim:Point>
            <cim:Point>
                <cim:position>2</cim:position>
                <cim:quantity>56</cim:quantity>
                <cim:quality>A03</cim:quality>
            </cim:Point>
            <cim:Point>
                <cim:position>3</cim:position>
                <cim:quantity>56</cim:quantity>
                <cim:quality>A03</cim:quality>
            </cim:Point>
            <cim:Point>
                <cim:position>4</cim:position>
                <cim:quantity>56</cim:quantity>
                <cim:quality>A03</cim:quality>
            </cim:Point>
            <cim:Point>
                <cim:position>5</cim:position>
                <cim:quantity>56</cim:quantity>
                <cim:quality>A03</cim:quality>
            </cim:Point>
            <cim:Point>
                <cim:position>6</cim:position>
                <cim:quantity>56</cim:quantity>
                <cim:quality>A03</cim:quality>
            </cim:Point>
        </cim:Period>
    </cim:Series>
</cim:NotifyValidatedMeasureData_MarketDocument>
