=== Energinet-DataHub/opengeh-edi/source/IncomingMessages.Infrastructure/DocumentValidation/CimXml/Schemas/urn-ediel-org-measure-requestwholesalesettlement-0-1.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:cim="urn:ediel.org:measure:requestwholesalesettlement:0:1" xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:sawsdl="http://www.w3.org/ns/sawsdl" xmlns:cimp="http://www.iec.ch/cimprofile" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:ediel.org:measure:requestwholesalesettlement:0:1" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:import namespace="urn:entsoe.eu:wgedi:codelists" schemaLocation="urn-entsoe-eu-wgedi-codelists.xsd"/>
	<xs:element name="RequestWholesaleSettlement_MarketDocument" type="cim:RequestWholesaleSettlement_MarketDocument"/>
	<xs:simpleType name="ChargeKind_String" sawsdl:modelReference="http://iec.ch/TC57/CIM101#String">
		<xs:restriction base="ecl:ChargeTypeList"/>
	</xs:simpleType>
	<xs:complexType name="ChargeType" sawsdl:modelReference="http://iec.ch/TC57/CIM101#ChargeType">
		<xs:sequence>
			<xs:element name="type" type="cim:ChargeKind_String" minOccurs="0" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/CIM101#Document.type"/>
			<xs:element name="mRID" type="xs:string" minOccurs="0" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/CIM101#IdentifiedObject.mRID"/>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="MessageKind_String" sawsdl:modelReference="http://iec.ch/TC57/CIM101#String">
		<xs:restriction base="ecl:MessageTypeList"/>
	</xs:simpleType>
	<xs:simpleType name="ProcessKind_String" sawsdl:modelReference="http://iec.ch/TC57/CIM101#String">
		<xs:restriction base="ecl:ProcessTypeList"/>
	</xs:simpleType>
	<xs:simpleType name="BusinessSectorKind_String" sawsdl:modelReference="http://iec.ch/TC57/CIM101#String">
		<xs:restriction base="ecl:BusinessSectorTypeList"/>
	</xs:simpleType>
	<xs:simpleType name="PartyID_String-base" sawsdl:modelReference="http://iec.ch/TC57/CIM101#String">
		<xs:restriction base="xs:string">
			<xs:maxLength value="16"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="PartyID_String" sawsdl:modelReference="http://iec.ch/TC57/CIM101#String">
		<xs:simpleContent>
			<xs:extension base="cim:PartyID_String-base">
				<xs:attribute name="codingScheme" type="ecl:CodingSchemeTypeList" use="required"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:simpleType name="MarketRoleKind_String" sawsdl:modelReference="http://iec.ch/TC57/CIM101#String">
		<xs:restriction base="ecl:RoleTypeList"/>
	</xs:simpleType>
	<xs:complexType name="RequestWholesaleSettlement_MarketDocument" sawsdl:modelReference="http://iec.ch/TC57/CIM101#MarketDocument">
		<xs:sequence>
			<xs:element name="mRID" type="xs:string" minOccurs="1" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/CIM101#IdentifiedObject.mRID"/>
			<xs:element name="type" type="cim:MessageKind_String" default="D21" minOccurs="1" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/CIM101#Document.type"/>
			<xs:element name="process.processType" type="cim:ProcessKind_String" minOccurs="1" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/CIM101#Process.processType"/>
			<xs:element name="businessSector.type" type="cim:BusinessSectorKind_String" minOccurs="0" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/CIM101#BusinessSector.type"/>
			<xs:element name="sender_MarketParticipant.mRID" type="cim:PartyID_String" minOccurs="1" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/CIM101#IdentifiedObject.mRID"/>
			<xs:element name="sender_MarketParticipant.marketRole.type" type="cim:MarketRoleKind_String" minOccurs="1" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/CIM101#MarketRole.type"/>
			<xs:element name="receiver_MarketParticipant.mRID" type="cim:PartyID_String" minOccurs="1" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/CIM101#IdentifiedObject.mRID"/>
			<xs:element name="receiver_MarketParticipant.marketRole.type" type="cim:MarketRoleKind_String" minOccurs="1" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/CIM101#MarketRole.type"/>
			<xs:element name="createdDateTime" type="xs:dateTime" minOccurs="1" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/CIM101#Document.createdDateTime"/>
			<xs:element name="Series" type="cim:Series" minOccurs="1" maxOccurs="unbounded" sawsdl:modelReference="http://iec.ch/TC57/CIM101#MarketDocument.Series"/>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="ProcessVariantKind_String" sawsdl:modelReference="http://iec.ch/TC57/CIM101#String">
		<xs:restriction base="ecl:ProcessVariantTypeList"/>
	</xs:simpleType>
	<xs:simpleType name="AreaID_String-base" sawsdl:modelReference="http://iec.ch/TC57/CIM101#String">
		<xs:restriction base="xs:string">
			<xs:maxLength value="18"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="AreaID_String" sawsdl:modelReference="http://iec.ch/TC57/CIM101#String">
		<xs:simpleContent>
			<xs:extension base="cim:AreaID_String-base">
				<xs:attribute name="codingScheme" type="ecl:CodingSchemeTypeList" use="required"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="Series" sawsdl:modelReference="http://iec.ch/TC57/CIM101#Series">
		<xs:sequence>
			<xs:element name="mRID" type="xs:string" minOccurs="1" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/CIM101#IdentifiedObject.mRID"/>
			<xs:element name="version" type="xs:string" minOccurs="0" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/CIM101#TimeSeries.version"/>
			<xs:element name="settlement_Series.version" type="cim:ProcessVariantKind_String" minOccurs="0" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/CIM101#TimeSeries.version"/>
			<xs:element name="start_DateAndOrTime.dateTime" type="xs:dateTime" minOccurs="1" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/CIM101#DateAndOrTime.dateTime"/>
			<xs:element name="end_DateAndOrTime.dateTime" type="xs:dateTime" minOccurs="0" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/CIM101#DateAndOrTime.dateTime"/>
			<xs:element name="meteringGridArea_Domain.mRID" type="cim:AreaID_String" minOccurs="0" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/CIM101#IdentifiedObject.mRID"/>
			<xs:element name="energySupplier_MarketParticipant.mRID" type="cim:PartyID_String" minOccurs="0" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/CIM101#IdentifiedObject.mRID"/>
			<xs:element name="chargeTypeOwner_MarketParticipant.mRID" type="cim:PartyID_String" minOccurs="0" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/CIM101#IdentifiedObject.mRID"/>
			<xs:element name="aggregationSeries_Period.resolution" type="xs:duration" minOccurs="0" maxOccurs="1" sawsdl:modelReference="http://iec.ch/TC57/CIM101#Period.resolution"/>
			<xs:element name="ChargeType" type="cim:ChargeType" minOccurs="0" maxOccurs="unbounded" sawsdl:modelReference="http://iec.ch/TC57/CIM101#Series.ChargeType"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== Energinet-DataHub/opengeh-edi/source/Tests/CimMessageAdapter/Messages/xml/WholesaleSettlement/RequestWholesaleSettlement2ChargeTypes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2021 rel. 3 (x64) (http://www.altova.com)-->
<cim:RequestWholesaleSettlement_MarketDocument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:cim="urn:ediel.org:measure:requestwholesalesettlement:0:1" xsi:schemaLocation="urn:ediel.org:measure:requestwholesalesettlement:0:1 urn-ediel-org-measure-requestwholesalesettlement-0-1.xsd">
    <cim:mRID>12345678</cim:mRID>
    <cim:type>D21</cim:type>
    <cim:process.processType>D05</cim:process.processType>
    <cim:businessSector.type>23</cim:businessSector.type>
    <cim:sender_MarketParticipant.mRID codingScheme="A10">5799999933318</cim:sender_MarketParticipant.mRID>
    <cim:sender_MarketParticipant.marketRole.type>DDQ</cim:sender_MarketParticipant.marketRole.type>
    <cim:receiver_MarketParticipant.mRID codingScheme="A10">5790001330552</cim:receiver_MarketParticipant.mRID>
    <cim:receiver_MarketParticipant.marketRole.type>DDZ</cim:receiver_MarketParticipant.marketRole.type> <!--ROLE uklar -->
    <cim:createdDateTime>2022-12-17T09:30:47Z</cim:createdDateTime>
    <cim:Series>
        <cim:mRID>25836143</cim:mRID>
        <cim:settlement_Series.version>D01</cim:settlement_Series.version>
        <cim:start_DateAndOrTime.dateTime>2022-08-17T22:00:00Z</cim:start_DateAndOrTime.dateTime>
        <cim:end_DateAndOrTime.dateTime>2022-08-31T22:00:00Z</cim:end_DateAndOrTime.dateTime>
        <cim:meteringGridArea_Domain.mRID codingScheme="NDK">244</cim:meteringGridArea_Domain.mRID>
        <cim:energySupplier_MarketParticipant.mRID codingScheme="A10">5799999933318</cim:energySupplier_MarketParticipant.mRID>
        <cim:chargeTypeOwner_MarketParticipant.mRID codingScheme="A10">570001110111</cim:chargeTypeOwner_MarketParticipant.mRID>
        <cim:aggregationSeries_Period.resolution>PT1M</cim:aggregationSeries_Period.resolution> <!-- kun i forbindelse med BRS-030 -->
        <cim:ChargeType>
            <cim:type>D03</cim:type>
            <cim:mRID>EA-001</cim:mRID>
        </cim:ChargeType>        
        <cim:ChargeType>
            <cim:type>D02</cim:type>
            <cim:mRID>EA-002</cim:mRID>
        </cim:ChargeType>
    </cim:Series>
</cim:RequestWholesaleSettlement_MarketDocument>

=== Energinet-DataHub/opengeh-edi/source/B2BApi.AppTests/TestData/Messages/xml/RequestWholesaleSettlementForEnergySupplier.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2021 rel. 3 (x64) (http://www.altova.com)-->
<cim:RequestWholesaleSettlement_MarketDocument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:cim="urn:ediel.org:measure:requestwholesalesettlement:0:1" xsi:schemaLocation="urn:ediel.org:measure:requestwholesalesettlement:0:1 urn-ediel-org-measure-requestwholesalesettlement-0-1.xsd">
    <cim:mRID>{MessageId}</cim:mRID>
    <cim:type>D21</cim:type>
    <cim:process.processType>D05</cim:process.processType>
    <cim:businessSector.type>23</cim:businessSector.type>
    <cim:sender_MarketParticipant.mRID codingScheme="A10">{ActorNumber}</cim:sender_MarketParticipant.mRID>
    <cim:sender_MarketParticipant.marketRole.type>{ActorRole}</cim:sender_MarketParticipant.marketRole.type>
    <cim:receiver_MarketParticipant.mRID codingScheme="A10">5790001330552</cim:receiver_MarketParticipant.mRID>
    <cim:receiver_MarketParticipant.marketRole.type>DGL</cim:receiver_MarketParticipant.marketRole.type>
    <cim:createdDateTime>2022-02-17T09:30:47Z</cim:createdDateTime>
    <cim:Series>
        <cim:mRID>{TransactionId}</cim:mRID>
        <!--cim:settlement_Series.version>D01</cim:settlement_Series.version-->
        <cim:start_DateAndOrTime.dateTime>2021-12-31T23:00:00Z</cim:start_DateAndOrTime.dateTime>
        <cim:end_DateAndOrTime.dateTime>2022-01-31T23:00:00Z</cim:end_DateAndOrTime.dateTime>
<!--        <cim:meteringGridArea_Domain.mRID codingScheme="NDK">543</cim:meteringGridArea_Domain.mRID>-->
        <cim:energySupplier_MarketParticipant.mRID codingScheme="A10">{ActorNumber}</cim:energySupplier_MarketParticipant.mRID>
<!--        <cim:chargeTypeOwner_MarketParticipant.mRID codingScheme="A10">5790000432752</cim:chargeTypeOwner_MarketParticipant.mRID>-->
<!--        <cim:ChargeType>-->
<!--            <cim:type>D03</cim:type>-->
<!--            <cim:mRID>42000</cim:mRID>-->
<!--        </cim:ChargeType>-->
    </cim:Series>
</cim:RequestWholesaleSettlement_MarketDocument>
