=== Energinet-DataHub/opengeh-edi/source/DocumentValidation/CimXml/Schemas/urn-ediel-org-measure-requestaggregatedmeasuredata-0-1.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:cim="urn:ediel.org:measure:requestaggregatedmeasuredata:0:1" xmlns:ecl="urn:entsoe.eu:wgedi:codelists" xmlns:sawsdl="http://www.w3.org/ns/sawsdl" xmlns:cimp="http://www.iec.ch/cimprofile" attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="urn:ediel.org:measure:requestaggregatedmeasuredata:0:1" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:import schemaLocation="urn-entsoe-eu-wgedi-codelists.xsd" namespace="urn:entsoe.eu:wgedi:codelists" />
    <xs:element name="RequestAggregatedMeasureData_MarketDocument" type="cim:RequestAggregatedMeasureData_MarketDocument" />
    <xs:simpleType name="MessageKind_String" sawsdl:modelReference="http://iec.ch/TC57/CIM101#String">
        <xs:restriction base="ecl:MessageTypeList" />
    </xs:simpleType>
    <xs:simpleType name="ProcessKind_String" sawsdl:modelReference="http://iec.ch/TC57/CIM101#String">
        <xs:restriction base="ecl:ProcessTypeList" />
    </xs:simpleType>
    <xs:simpleType name="BusinessSectorKind_String" sawsdl:modelReference="http://iec.ch/TC57/CIM101#String">
        <xs:restriction base="ecl:BusinessSectorTypeList" />
    </xs:simpleType>
    <xs:simpleType name="PartyID_String-base" sawsdl:modelReference="http://iec.ch/TC57/CIM101#String">
        <xs:restriction base="xs:string">
            <xs:maxLength value="16" />
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="PartyID_String" sawsdl:modelReference="http://iec.ch/TC57/CIM101#String">
        <xs:simpleContent>
            <xs:extension base="cim:PartyID_String-base">
                <xs:attribute name="codingScheme" type="ecl:CodingSchemeTypeList" use="required" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:simpleType name="MarketRoleKind_String" sawsdl:modelReference="http://iec.ch/TC57/CIM101#String">
        <xs:restriction base="ecl:RoleTypeList" />
    </xs:simpleType>
    <xs:complexType name="RequestAggregatedMeasureData_MarketDocument" sawsdl:modelReference="http://iec.ch/TC57/CIM101#MarketDocument">
        <xs:sequence>
            <xs:element minOccurs="1" maxOccurs="1" name="mRID" type="xs:string" sawsdl:modelReference="http://iec.ch/TC57/CIM101#IdentifiedObject.mRID">
            </xs:element>
            <xs:element minOccurs="1" maxOccurs="1" default="E74" name="type" type="cim:MessageKind_String" sawsdl:modelReference="http://iec.ch/TC57/CIM101#Document.type">
            </xs:element>
            <xs:element minOccurs="1" maxOccurs="1" name="process.processType" type="cim:ProcessKind_String" sawsdl:modelReference="http://iec.ch/TC57/CIM101#Process.processType">
            </xs:element>
            <xs:element minOccurs="0" maxOccurs="1" name="businessSector.type" type="cim:BusinessSectorKind_String" sawsdl:modelReference="http://iec.ch/TC57/CIM101#BusinessSector.type">
            </xs:element>
            <xs:element minOccurs="1" maxOccurs="1" name="sender_MarketParticipant.mRID" type="cim:PartyID_String" sawsdl:modelReference="http://iec.ch/TC57/CIM101#IdentifiedObject.mRID">
            </xs:element>
            <xs:element minOccurs="1" maxOccurs="1" name="sender_MarketParticipant.marketRole.type" type="cim:MarketRoleKind_String" sawsdl:modelReference="http://iec.ch/TC57/CIM101#MarketRole.type">
            </xs:element>
            <xs:element minOccurs="1" maxOccurs="1" name="receiver_MarketParticipant.mRID" type="cim:PartyID_String" sawsdl:modelReference="http://iec.ch/TC57/CIM101#IdentifiedObject.mRID">
            </xs:element>
            <xs:element minOccurs="1" maxOccurs="1" name="receiver_MarketParticipant.marketRole.type" type="cim:MarketRoleKind_String" sawsdl:modelReference="http://iec.ch/TC57/CIM101#MarketRole.type">
            </xs:element>
            <xs:element minOccurs="1" maxOccurs="1" name="createdDateTime" type="xs:dateTime" sawsdl:modelReference="http://iec.ch/TC57/CIM101#Document.createdDateTime">
            </xs:element>
            <xs:element minOccurs="1" maxOccurs="unbounded" name="Series" type="cim:Series" sawsdl:modelReference="http://iec.ch/TC57/CIM101#MarketDocument.Series">
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="ProcessVariantKind_String" sawsdl:modelReference="http://iec.ch/TC57/CIM101#String">
        <xs:restriction base="ecl:ProcessVariantTypeList" />
    </xs:simpleType>
    <xs:simpleType name="MarketEvaluationPointKind_String" sawsdl:modelReference="http://iec.ch/TC57/CIM101#String">
        <xs:restriction base="ecl:MeteringPointTypeList" />
    </xs:simpleType>
    <xs:simpleType name="SettlementMethodKind_String" sawsdl:modelReference="http://iec.ch/TC57/CIM101#String">
        <xs:restriction base="ecl:SettlementMethodTypeList" />
    </xs:simpleType>
    <xs:simpleType name="AreaID_String-base" sawsdl:modelReference="http://iec.ch/TC57/CIM101#String">
        <xs:restriction base="xs:string">
            <xs:maxLength value="18" />
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="AreaID_String" sawsdl:modelReference="http://iec.ch/TC57/CIM101#String">
        <xs:simpleContent>
            <xs:extension base="cim:AreaID_String-base">
                <xs:attribute name="codingScheme" type="ecl:CodingSchemeTypeList" use="required" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="Series" sawsdl:modelReference="http://iec.ch/TC57/CIM101#Series">
        <xs:sequence>
            <xs:element minOccurs="1" maxOccurs="1" name="mRID" type="xs:string" sawsdl:modelReference="http://iec.ch/TC57/CIM101#IdentifiedObject.mRID">
            </xs:element>
            <xs:element minOccurs="0" maxOccurs="1" name="settlement_Series.version" type="cim:ProcessVariantKind_String" sawsdl:modelReference="http://iec.ch/TC57/CIM101#TimeSeries.version">
            </xs:element>
            <xs:element minOccurs="0" maxOccurs="1" name="marketEvaluationPoint.type" type="cim:MarketEvaluationPointKind_String" sawsdl:modelReference="http://iec.ch/TC57/CIM101#Ext_MarketEvaluationPoint.type">
            </xs:element>
            <xs:element minOccurs="0" maxOccurs="1" name="marketEvaluationPoint.settlementMethod" type="cim:SettlementMethodKind_String" sawsdl:modelReference="http://iec.ch/TC57/CIM101#Ext_MarketEvaluationPoint.settlementMethod">
            </xs:element>
            <xs:element minOccurs="1" maxOccurs="1" name="start_DateAndOrTime.dateTime" type="xs:dateTime" sawsdl:modelReference="http://iec.ch/TC57/CIM101#DateAndOrTime.dateTime">
            </xs:element>
            <xs:element minOccurs="0" maxOccurs="1" name="end_DateAndOrTime.dateTime" type="xs:dateTime" sawsdl:modelReference="http://iec.ch/TC57/CIM101#DateAndOrTime.dateTime">
            </xs:element>
            <xs:element minOccurs="0" maxOccurs="1" name="meteringGridArea_Domain.mRID" type="cim:AreaID_String" sawsdl:modelReference="http://iec.ch/TC57/CIM101#IdentifiedObject.mRID">
            </xs:element>
            <xs:element minOccurs="0" maxOccurs="1" name="biddingZone_Domain.mRID" type="cim:AreaID_String" sawsdl:modelReference="http://iec.ch/TC57/CIM101#IdentifiedObject.mRID">
            </xs:element>
            <xs:element minOccurs="0" maxOccurs="1" name="energySupplier_MarketParticipant.mRID" type="cim:PartyID_String" sawsdl:modelReference="http://iec.ch/TC57/CIM101#IdentifiedObject.mRID">
            </xs:element>
            <xs:element minOccurs="0" maxOccurs="1" name="balanceResponsibleParty_MarketParticipant.mRID" type="cim:PartyID_String" sawsdl:modelReference="http://iec.ch/TC57/CIM101#IdentifiedObject.mRID">
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== Energinet-DataHub/opengeh-edi/source/Tests/CimMessageAdapter/Messages/xml/AggregatedMeasure/TwoSeriesRequestAggregatedMeasureData.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright 2020 Energinet DataHub A/S

Licensed under the Apache License, Version 2.0 (the "License2");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->
<cim:RequestAggregatedMeasureData_MarketDocument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:cim="urn:ediel.org:measure:requestaggregatedmeasuredata:0:1" xsi:schemaLocation="urn:ediel.org:measure:requestaggregatedmeasuredata:0:1 urn-ediel-org-measure-requestaggregatedmeasuredata-0-1.xsd">
    <cim:mRID>123564789123564789123564789123564789</cim:mRID>
    <cim:type>E74</cim:type>
    <cim:process.processType>D05</cim:process.processType>
    <cim:businessSector.type>23</cim:businessSector.type>
    <cim:sender_MarketParticipant.mRID codingScheme="A10">5799999933318</cim:sender_MarketParticipant.mRID>
    <cim:sender_MarketParticipant.marketRole.type>DDK</cim:sender_MarketParticipant.marketRole.type>
    <cim:receiver_MarketParticipant.mRID codingScheme="A10">5790001330552</cim:receiver_MarketParticipant.mRID>
    <cim:receiver_MarketParticipant.marketRole.type>DGL</cim:receiver_MarketParticipant.marketRole.type>
    <cim:createdDateTime>2022-12-17T09:30:47Z</cim:createdDateTime>
    <cim:Series>
        <cim:mRID>123353185</cim:mRID>
        <cim:settlement_Series.version>D01</cim:settlement_Series.version>
        <cim:marketEvaluationPoint.type>E17</cim:marketEvaluationPoint.type>
        <cim:marketEvaluationPoint.settlementMethod>D01</cim:marketEvaluationPoint.settlementMethod>
        <cim:start_DateAndOrTime.dateTime>2022-06-17T22:00:00Z</cim:start_DateAndOrTime.dateTime>
        <cim:end_DateAndOrTime.dateTime>2022-07-22T22:00:00Z</cim:end_DateAndOrTime.dateTime>
        <cim:meteringGridArea_Domain.mRID codingScheme="NDK">244</cim:meteringGridArea_Domain.mRID>
        <cim:biddingZone_Domain.mRID codingScheme="A01">10YDK-1--------M</cim:biddingZone_Domain.mRID> <!-- anvendes ikke -->
        <cim:energySupplier_MarketParticipant.mRID codingScheme="A10">5790001330552</cim:energySupplier_MarketParticipant.mRID>
        <cim:balanceResponsibleParty_MarketParticipant.mRID codingScheme="A10">5799999933318</cim:balanceResponsibleParty_MarketParticipant.mRID>
    </cim:Series>
    <cim:Series>
        <cim:mRID>123353185</cim:mRID>
        <cim:settlement_Series.version>D01</cim:settlement_Series.version>
        <cim:marketEvaluationPoint.type>E17</cim:marketEvaluationPoint.type>
        <cim:marketEvaluationPoint.settlementMethod>D01</cim:marketEvaluationPoint.settlementMethod>
        <cim:start_DateAndOrTime.dateTime>2022-06-17T22:00:00Z</cim:start_DateAndOrTime.dateTime>
        <cim:end_DateAndOrTime.dateTime>2022-07-22T22:00:00Z</cim:end_DateAndOrTime.dateTime>
        <cim:meteringGridArea_Domain.mRID codingScheme="NDK">244</cim:meteringGridArea_Domain.mRID>
        <cim:biddingZone_Domain.mRID codingScheme="A01">10YDK-1--------M</cim:biddingZone_Domain.mRID> <!-- anvendes ikke -->
        <cim:energySupplier_MarketParticipant.mRID codingScheme="A10">5790001330552</cim:energySupplier_MarketParticipant.mRID>
        <cim:balanceResponsibleParty_MarketParticipant.mRID codingScheme="A10">5799999933318</cim:balanceResponsibleParty_MarketParticipant.mRID>
    </cim:Series>
</cim:RequestAggregatedMeasureData_MarketDocument>
